
---

- name: CIS 1
  hosts: AnsibleTestPlaybooks
  user: eme1m8u
  sudo: true

  tasks:


 # CIS Section 6 Scored
  - name: Set Permissions on /etc/ssh/sshd_config -rw
    file: path=/etc/ssh/sshd_config mode=0600
  - name: Disabling SELINUX
    lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=disabled
 # Run only this play with the tag by using --selinux
    tags:
       - selinux
  - name: Disabling SSH X11 Forwarding
    replace: dest=/etc/ssh/sshd_config regexp='X11Forwarding yes' replace='X11Forwarding no'
    tags:
       - x11
  - name: Set SSH MAXAUTHTRIES to 4 or less
    replace: dest=/etc/ssh/sshd_config regexp='MaxAuthTries 6' replace='MaxAuthTries 4'
  - name: Set SSH IgnoreRhosts to yes
    replace: dest=/etc/ssh/sshd_config regexp=^'IgnoreRhosts no' replace='IgnoreRhosts yes'
  - name: Disable SSH Root Login
    replace: dest=/etc/ssh/sshd_config regexp='PermitRootLogin yes' replace='PermitRootLogin no'
  - name: Set SSH HostBasedAuthentication to No
    replace: dest=/etc/ssh/sshd_config regexp='HostbasedAuthentication yes' replace='HostbasedAuthentication no'
  - name: Don't allow users to set Environ. Options
    replace: dest=/etc/ssh/sshd_config regexp='PermitUserEnvironment yes' replace='PermitUserEnvironment no'




 # CIS BenchMarks section 1 level 1 all scored

  

  - name: upgrading all packages
    yum: name=* state=latest
  - name: 1.3.2 Implement Periodic Execution of File Integrity
    action: cron name="Run AIDE (CIS 1.3.2)" minute="0" hour="5" job="/usr/sbin/aide --check"
  - name: installing libselinux - Python
    yum: name=libselinux-python state=latest
  - name: 1.4.2/1.4.3 Set the SELinux State/Policy (install targeted)
    yum: name=selinux-policy-targeted state=present
  - name: 1.4.2/1.4.3 Set the SELinux State/Policy
    selinux: state=enforcing policy=targeted
  - name: 1.4.5 Remove MCS Translation Service
    yum: name=mcstrans state=absent
  - name: 1.5.1 Set User/Group Owner on /etc/grub.conf
    file: path=/boot/grub/grub.conf owner=root group=root
  - name: 1.5.2 Set Permissions on /etc/grub.conf
    file: path=/boot/grub/grub.conf mode=0400
  - name: 1.5.5 Disable Interactive Boot
    lineinfile: dest=/etc/sysconfig/init regexp=^PROMPT= line=PROMPT=no

  # CIS Section 2 level 1 Scored

  - name: Removing the Talk-server (allows servers to communicate through CLI)
    yum: name=talk-server state=absent
  - name: removing NIS Client
    yum: name=ypbind state=absent
  - name: removing RSH (contains the client commands for RSH)
    yum: name=rsh state=absent
  - name: removing tftp (trivial transfer protocol)
    yum: name=tftp state=absent
  - name: removing tftp-server (automatically transfer config tool to or boot machines)
    yum: name=tftp-server state=absent
  - name: removing the "talk" (removes the process of sending and receiving messages)
    yum: name=talk state=absent
  - name: removing Dovecot
    yum: name=dovecot state=absent
  - name: removing SNMP server
    yum: name=net-snmp state=absent

  # CIS Benchmarks Section 3 Level 1 all scored

  - name: 1.5.2 Set Permissions on /etc/grub.conf
    file: path=/boot/grub/grub.conf mode=0400
  - name: 1.5.5 Disable Interactive Boot
    lineinfile: dest=/etc/sysconfig/init regexp=^PROMPT= line=PROMPT=no

  # CIS Section 2 level 1 Scored

  - name: Removing the Talk-server (allows servers to communicate through CLI)
    yum: name=talk-server state=absent
  - name: removing NIS Client
    yum: name=ypbind state=absent
  - name: removing RSH (contains the client commands for RSH)
    yum: name=rsh state=absent
  - name: removing tftp (trivial transfer protocol)
    yum: name=tftp state=absent
  - name: removing tftp-server (automatically transfer config tool to or boot machines)
    yum: name=tftp-server state=absent
  - name: removing the "talk" (removes the process of sending and receiving messages)
    yum: name=talk state=absent
  - name: removing Dovecot
    yum: name=dovecot state=absent
  - name: removing SNMP server
    yum: name=net-snmp state=absent

  # CIS Benchmarks Section 3 Level 1 all scored

  - name: 2.1.1 Remove telnet-server
    yum: name=telnet-server state=absent
  - name: 2.1.2 Remove telnet Clients
    yum: name=telnet state=absent
  - name: 2.1.3 Remove rsh-server
    yum: name=rsh-server state=absent
  - name: 2.1.4 Remove rsh
    yum: name=rsh state=absent
  - name: 2.1.5 Remove NIS Client
    yum: name=ypbind state=absent
  - name: 2.1.6 Remove NIS Server
    yum: name=ypserv state=absent
  - name: 2.1.7 Remove tftp
    yum: name=tftp state=absent
  - name: 2.1.8 Remove tftp-server
    yum: name=tftp-server state=absent
  - name: 2.1.9 Remove talk
    yum: name=talk state=absent
  - name: 2.1.10 Remove talk-server
    yum: name=talk-server state=absent
  - name: 2.1.11 Remove xinetd
    yum: name=xinetd state=absent
  - name: 2.1.12 Disable chargen-dgram
    debug: msg="Not needed. xinetd is already uninstalled."
  - name: 2.1.13 Disable chargen-stream

  - name: 2.1.1 Remove telnet-server
    yum: name=telnet-server state=absent
  - name: 2.1.2 Remove telnet Clients
    yum: name=telnet state=absent
  - name: 2.1.3 Remove rsh-server
    yum: name=rsh-server state=absent
  - name: 2.1.4 Remove rsh
    yum: name=rsh state=absent
  - name: 2.1.5 Remove NIS Client
    yum: name=ypbind state=absent
  - name: 2.1.6 Remove NIS Server
    yum: name=ypserv state=absent
  - name: 2.1.7 Remove tftp
    yum: name=tftp state=absent
  - name: 2.1.8 Remove tftp-server
    yum: name=tftp-server state=absent
  - name: 2.1.9 Remove talk
    yum: name=talk state=absent
  - name: 2.1.10 Remove talk-server
    yum: name=talk-server state=absent
  - name: 2.1.11 Remove xinetd
    yum: name=xinetd state=absent
  - name: 2.1.12 Disable chargen-dgram
    debug: msg="Not needed. xinetd is already uninstalled."
  - name: 2.1.13 Disable chargen-stream
    debug: msg="Not needed. xinetd is already uninstalled."
  - name: 2.1.14 Disable daytime-dgram
    debug: msg="Not needed. xinetd is already uninstalled."
  - name: 2.1.15 Disable daytime-stream
    debug: msg="Not needed. xinetd is already uninstalled."
  - name: 2.1.16 Disable echo-dgram
    debug: msg="Not needed. xinetd is already uninstalled."
  - name: 2.1.17 Disable echo-stream
    debug: msg="Not needed. xinetd is already uninstalled."
  - name: 2.1.18 Disable tcpmux-server
    debug: msg="Not needed. xinetd is already uninstalled."
  - name: 3.1 Set Daemon umask
    lineinfile: dest=/etc/sysconfig/init state=present regexp=^umask line="umask 027"
  - name: 3.2 Remove X Windows (runlevel 3)
    lineinfile: dest=/etc/inittab state=present regexp="^id:" line="id:3:initdefault:"
  - name: 3.2 Remove X Windows (remove package group)
    yum: name="@X Window System" state=absent
  - name: 3.3 Disable Avahi Server
    command: chkconfig avahi-daemon off removes=/etc/rc.d/rc3.d/S24avahi-daemon
  - name: 3.5 Remove DHCP Server
    yum: name=dhcp state=absent


  # These are not scored by CIS but are level 1

  - name: 2.1.13 Disable chargen-stream
    debug: msg="Not needed. xinetd is already uninstalled."
  - name: 2.1.14 Disable daytime-dgram
    debug: msg="Not needed. xinetd is already uninstalled."
  - name: 2.1.15 Disable daytime-stream
    debug: msg="Not needed. xinetd is already uninstalled."
  - name: 2.1.16 Disable echo-dgram
    debug: msg="Not needed. xinetd is already uninstalled."
  - name: 2.1.17 Disable echo-stream
    debug: msg="Not needed. xinetd is already uninstalled."
  - name: 2.1.18 Disable tcpmux-server
    debug: msg="Not needed. xinetd is already uninstalled."
  - name: 3.1 Set Daemon umask
    lineinfile: dest=/etc/sysconfig/init state=present regexp=^umask line="umask 027"
  - name: 3.2 Remove X Windows (runlevel 3)
    lineinfile: dest=/etc/inittab state=present regexp="^id:" line="id:3:initdefault:"
  - name: 3.2 Remove X Windows (remove package group)
    yum: name="@X Window System" state=absent
  - name: 3.3 Disable Avahi Server
    command: chkconfig avahi-daemon off removes=/etc/rc.d/rc3.d/S24avahi-daemon
  - name: 3.5 Remove DHCP Server
    yum: name=dhcp state=absent


  # These are not scored by CIS but are level 1

  - name: Disbling and removing CUPS
    yum: name=cups state=absent
  - name: removing Samba
    yum: name=samba state=absent

  # CIS section 4 Logging and auditing

  - name: Rsyslong installation
    yum: name=rsyslog state=latest

